### ISSUE TITLE
input 自动focus 没必要啊

### ISSUE THREAD

**Issue by 1sm23** [996mmp/996mmp#1]
很长内容的主题点进去又要手动滚上去 建议增加到顶按钮

**Comment by 996mmp** [comment]
@gromit1sm 你说的问题在Vivaldi浏览器(目前基于Chrome 79）上没出现，但在Opera（目前基于Chrome 78）和Firefox 71上复现了。

不太会写前端，所以该问题和“增加到顶按钮的”建议会比较慢修复。
可能Chrome 79不会出现该问题

**Comment by 996mmp** [comment]
@gromit1sm 已经修复了
